version: '3'
services:
  
  
  db:
    depends_on:
      - elasticsearch
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - lamp-docker
  
  
  www:
    depends_on:
      - db
      - elasticsearch
    #image: php:8.1-apache
    build: './'
    volumes:
      - "./www:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker
  
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_POST=3306
    networks:
      - lamp-docker      


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: vstay_elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=datasearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data 
    networks:
      - lamp-docker      


networks:
  lamp-docker:
    driver: bridge